973 missing detail in grid documentation
ploomber/ploomber pull request #1020
Opened 2022-09-12 17:17 UTC by shizuchanw

## Describe your changes
based on [PR: 988](https://github.com/ploomber/ploomber/pull/988), fixed flake8 issue and checked documentation.

## Issue ticket number and link
Closes #973 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [x] I have added thorough tests (when necessary).
- [x] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

2022-09-28 00:38 UTC, edublancas commented
so this is a replacement of https://github.com/ploomber/ploomber/pull/988, right?

2022-09-28 01:12 UTC, shizuchanw commented
> so this is a replacement of #988, right?

Yes, I wasn’t able to directly commit to #988 so I created a new branch and copied the changes.

2022-10-24 20:45 UTC, edublancas requested changes

2022-10-24 20:45 UTC, edublancas commented on src/ploomber/spec/taskspec.py
> +            grid_number_suffix = data.pop('grid_number_suffix', False)
the default should be True, so we dont break existing pipelines. please change the default, update the tests (if anything breaks) and update the documentation

2023-06-02 02:49 UTC, closed without merging