added param example on documentation
ploomber/ploomber pull request #1029
Opened 2022-10-06 16:38 UTC by Mustapha-AJEGHRIR

## Describe your changes
@idomic 
I have added the parameterized exemple in the `basic-concepts.rst` for documentation as in the issue #965.

## Issue ticket number and link
Related to #965 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have added thorough tests (when necessary).
- [ ] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

2022-10-12 12:02 UTC, Mustapha-AJEGHRIR commented
@idomic Should I add something else ?

2022-10-14 19:29 UTC, edublancas requested changes

2022-10-14 19:29 UTC, edublancas commented on doc/get-started/basic-concepts.rst
> +It is also possible to use environment variables in the ``pipeline.yaml`` file.
please replace "environment variables" for "placeholders" since that's how we refer to the in the rest of the docs

2022-10-19 14:00 UTC, Mustapha-AJEGHRIR commented
@edublancas Is it Ok now ?

2022-10-20 19:26 UTC, edublancas approved these changes

2022-10-20 19:26 UTC, merged