Adding rst tips
ploomber/ploomber pull request #567
Opened 2022-02-09 05:49 UTC by lfunderburk

This PR contributes to https://github.com/ploomber/ploomber/issues/552

Added starting points plus further reading.

2022-02-09 14:07 UTC, edublancas requested changes

2022-02-09 14:07 UTC, edublancas commented on .gitignore
> +$HOME/.pyenv/pyenv_win-2.64.11.dist-info/METADATA
can you revert the changes to .gitignore? these are only applicable  to your setup

2022-02-10 03:36 UTC, lfunderburk commented
@edublancas reverted. Let me know if it looks ok

2022-02-10 03:37 UTC, edublancas commented
looks great! thanks for your contribution!

2022-02-10 03:38 UTC, merged