Updated documentation for nb cli functionality in similar method as nb --help.
ploomber/ploomber pull request #730
Opened 2022-04-30 22:00 UTC by mbebic

This pr links to issue #633 .

2022-05-05 07:58 UTC, idomic commented
@mbebic can you please rebase on the master to make sure the CI is passing?
Also, make sure you include all of the nb functionality, I've seen some weren't included, like pair, sync, format etc. You can view the commands via the `ploomber nb --help`

2022-05-05 07:58 UTC, idomic commented on doc/api/cli.rst
> +    ploomber nb --inject
Make sure you include the rest of the functionalities of this command

2022-05-05 07:59 UTC, idomic requested changes
Please fix and recommit

2022-05-07 01:15 UTC, merged

2022-05-07 01:15 UTC, edublancas commented
thanks for your contribution!