Changed typos from 'plomber' to 'ploomber'.
ploomber/ploomber pull request #732
Opened 2022-04-30 22:27 UTC by RobsonGlasscock

Files modified were: setup.py, cloud.py, nb.py, and notebooksource.py.

2022-05-01 08:13 UTC, idomic commented on setup.py
> +    #'psycopg2',
Please make sure it's enabled.

2022-05-01 08:14 UTC, idomic requested changes
Looks good besides the psycopg2 change, please fix

2022-05-01 18:59 UTC, RobsonGlasscock commented
Thank you for the feedback. The change has been made.

2022-05-05 07:50 UTC, idomic commented
@RobsonGlasscock please make sure the CI is passing, (rebasing on the master should solve this)

2022-05-05 15:43 UTC, closed without merging