Improved error message
ploomber/ploomber pull request #775
Opened 2022-05-17 05:19 UTC by aadityasinha-dotcom

Improved error message whenever a user passes `products` instead of `product` using `difflib`.
Resolves #642

2022-05-17 12:50 UTC, edublancas commented
can you add a test?

2022-05-17 13:09 UTC, aadityasinha-dotcom commented
> can you add a test?

Yeah sure!!

2022-05-18 01:27 UTC, edublancas requested changes

2022-05-18 01:27 UTC, edublancas commented on tests/util/test_util.py
> +    assert x == True
this test is not relevant. please test the changes that you introduced. in other words, that if the function has a `products` argument, you get the new error suggesting to change it to `product`

2022-05-19 07:19 UTC, aadityasinha-dotcom commented
@edublancas I have made the changes.

2022-05-19 13:28 UTC, edublancas requested changes

2022-05-19 13:47 UTC, edublancas commented
correct!

> On 19 May 2022, at 8:39, Aaditya Sinha ***@***.***> wrote:
> 
> 
> @aadityasinha-dotcom commented on this pull request.
> 
> In tests/util/test_util.py <https://github.com/ploomber/ploomber/pull/775#discussion_r877069366>:
> 
> > +from ploomber.util.util import signature_check
> +
> +def get(products):
> +    """Get data
> +    """
> +    d = datasets.load_iris()
> +
> +    df = pd.DataFrame(d['data'])
> +    df.columns = d['feature_names']
> +    df['target'] = d['target']
> +
> +    Path(str(product)).parent.mkdir(exist_ok=True, parents=True)
> +
> +    df.to_parquet(str(product))
> +
> +def test_signature_check():
> okay, so I have to test the pipeline, not the function.
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/ploomber/ploomber/pull/775#discussion_r877069366>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AAHRQQXDIEWLLVE2N3UFXITVKZACLANCNFSM5WDUILSQ>.
> You are receiving this because you were mentioned.
>

2022-05-20 14:04 UTC, aadityasinha-dotcom commented
@edublancas how can I test the pipeline as `signature_check` is verifying the function not the pipeline I tried using `PythonCallableSource` but didn't get the expected error.

2022-05-20 15:27 UTC, edublancas commented
using PythonCallable should work, upload the test that you tried to see what's missing

2022-05-20 15:31 UTC, aadityasinha-dotcom commented
okay

2022-05-21 17:56 UTC, closed without merging

2022-05-22 06:37 UTC, aadityasinha-dotcom commented
Was the PR incorrect?