Updated info in parallel to the template #684
ploomber/ploomber pull request #833
Opened 2022-06-03 20:48 UTC by qixuan27

## Describe your changes
Missing info in parallel to the template #684

## Issue ticket number and link
Closes #684 https://github.com/ploomber/ploomber/issues/684

## Checklist before requesting a review
- [ ] I have performed a self-review of my code
- [ ] I have added thorough tests (when necessary).
- [ ] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

2022-06-03 21:10 UTC, edublancas requested changes

2022-06-03 21:10 UTC, edublancas commented on doc/get-started/sql-pipeline.rst
> +You can also refer to https://github.com/ploomber/projects/blob/master/templates/spec-api-sql/README.ipynb for more information on using SQL scripts to manipulate data in a database, dump a table, an
please add the readme link using .rst link format:

```rst
`Link text <link URL>`_
```

https://sublime-and-sphinx-guide.readthedocs.io/en/latest/references.html

2022-06-03 21:10 UTC, edublancas commented on doc/get-started/sql-pipeline.rst
> +.. code-block:: txt
no need to put the sample output here

2022-06-03 21:10 UTC, edublancas commented on doc/get-started/sql-pipeline.rst
> +    %%bash
please remove the %%bash - this only works in jupyter/ipython

2022-06-06 20:39 UTC, idomic commented
@qixuan27 Did you run the PR locally and checked it looks like you're expecting?
Also a comment for next PRs try to be specific with your commit messages, looks like all of your commits are "Update sql-pipeline.rst" which is quite confusing and hard to revert.
A few more things you can try to improve is auto linting, and self code review before committing/pushing like we discussed.

2022-06-06 20:58 UTC, qixuan27 commented
Yes, I did. The current flow works well for ploomber/projects.
Sorry for the inconvenience. I did not comment for every update so the GitHub automatically commented on my commits like this. I will comment on each commit more precisely and use auto-linting before submitting pr.

2022-06-06 21:19 UTC, idomic commented
Sounds good, overall good job!

2022-06-06 21:19 UTC, merged