Add IFrame and remove requests_html
ploomber/ploomber pull request #890
Opened 2022-07-02 11:01 UTC by imskr

## Describe your changes

- Add `IFrame` and remove `requests_html` to display embedded D3 plot.
## Issue ticket number and link
Closes #842 

## Checklist before requesting a review
- [x] I have performed a self-review of my code
- [ ] I have added thorough tests (when necessary).
- [ ] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

2022-07-02 11:02 UTC, imskr commented
/cc @edublancas

2022-07-03 15:13 UTC, edublancas requested changes

2022-07-03 15:13 UTC, edublancas commented on src/ploomber/dag/plot.py
>            pip_names=['requests-html', 'nest_asyncio'])
we dont need this decorator anymore

2022-07-03 15:13 UTC, edublancas commented on src/ploomber/dag/plot.py
>      import asyncio
we dont need this

2022-07-03 15:13 UTC, edublancas commented on src/ploomber/dag/plot.py
> +    from IPython.display import IFrame
move import to the top

2022-07-03 15:13 UTC, edublancas commented on src/ploomber/dag/plot.py
> +    return asyncio.get_event_loop().run_until_complete(IFrame(src=path))
we dont need any of these, just return IFrame

2022-07-03 16:15 UTC, imskr commented
Thanks @edublancas I've made the changes as suggested :)

2022-07-05 01:11 UTC, edublancas commented
can you fix the tests? looks like you're missing some arguments

```

    def embedded_html(path):
>       return IFrame(src=path)
E       TypeError: __init__() missing 2 required positional arguments: 'width' and 'height'

```

2022-07-29 03:07 UTC, edublancas commented
closing due to inactivity

2022-07-29 03:07 UTC, closed without merging