Fixed confusing error when passing something.html as source #646
ploomber/ploomber pull request #920
Opened 2022-07-19 08:54 UTC by yafimvo

## Describe your changes
1. "_looks_like_path" checks a path. I've added another check if the user passed just a file name (is_path is false). We check if this file has a known extension with mimetypes. If so, this should throw the appropriate error ("Invalid extension"). Otherwise, it might be a dotted path.
2. "If you meant to import a function, please rename it." added at the end of the existing error message since there's a slight chance of a false positive where the user really wants to import a function named as the file's extension. 
3. A single file name without a path added to existing test function (test_task_class_from_script_unknown_extension)

## Issue ticket number and link
Issue number: 646
[Closes #x ](https://github.com/ploomber/ploomber/issues/646)

## Checklist before requesting a review
- [X ] I have performed a self-review of my code
- [X ] I have added thorough tests (when necessary).
- [ ] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

2022-07-19 12:58 UTC, idomic commented
@yafimvo Is this ready for review? 
Also please fix the ci

2022-07-19 15:30 UTC, 94rain commented
Seems that `_looks_like_path` will be evaluated to true for `.a` extensions with the changes, which raises the exception and causes `tests/spec/test_dagspec.py::test_python_callables_with_extract_upstream` to fail. I'm not very familiar with this part. Should we move the `elif` to a later point?

```python
>>> import mimetypes
>>> mimetypes.guess_type('a.a')
('application/octet-stream', None)
```


https://github.com/ploomber/ploomber/blob/c00102227cfb9f8650e0bc49b6780a7b1b6f562f/src/ploomber/spec/taskspec.py#L94-L99

2022-07-20 07:28 UTC, yafimvo commented
1. Restored `_looks_like_path` to its original implementation. 
2. Removed `mimetypes.guess_type` check
3. The error message 'If you meant to import a function, please rename it.' was added to a later point (after import fails)

If it's not a path it might be a dotted path (even with a name such as 'file.a'), so we try to import it. If the import fails it might be because of an invalid extension.

2022-07-20 13:16 UTC, idomic commented on tests/spec/test_taskspec.py
> +    str(Path('file.b'))
looks like this test is failing

2022-07-20 17:58 UTC, idomic commented
/ok-to-test sha=eb4e8d1

2022-07-20 19:04 UTC, idomic approved these changes
lgtm!
Nice job

2022-07-20 19:41 UTC, idomic commented
@yafimvo please make sure it behaves as expected,
I tried running `ploomber task sample -f` and `ploomber build -f` on this pipeline.yaml:
```
tasks:
  - source: sample.html
    product: output/nb.ipynb
    name: sample
```

The expected behavior was seeing the exception, but it actually tried running the task and complaining on missing out:

```
ploomber task sample -f
Loading pipeline...
100%|███████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 747.91it/s]
Traceback (most recent call last):
  File "/Documents/ploomber/ploomber/src/ploomber/tasks/abc.py", line 583, in _build
    self._post_run_actions()
  File "/Documents/ploomber/ploomber/src/ploomber/tasks/abc.py", line 376, in _post_run_actions
    raise TaskBuildError(f'Error building task {self.name!r}: '
ploomber.exceptions.TaskBuildError: Error building task 'sample': the task ran successfully but the product File('output/nb.ipynb') is missing. Ensure your code is generating it.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Documents/ploomber/ploomber/src/ploomber/cli/io.py", line 52, in wrapper
    fn(**kwargs)
  File "/Documents/ploomber/ploomber/src/ploomber/telemetry/telemetry.py", line 500, in wrapper
    raise e
  File "/Documents/ploomber/ploomber/src/ploomber/telemetry/telemetry.py", line 488, in wrapper
    result = func(*args, **kwargs)
  File "/Documents/ploomber/ploomber/src/ploomber/cli/task.py", line 76, in main
    _task_cli()
  File "/Documents/ploomber/ploomber/src/ploomber/cli/task.py", line 61, in _task_cli
    task.build(force=args.force)
  File "/Documents/ploomber/ploomber/src/ploomber/tasks/abc.py", line 522, in build
    res, _ = self._build(catch_exceptions=catch_exceptions)
  File "/Documents/ploomber/ploomber/src/ploomber/tasks/abc.py", line 595, in _build
    raise TaskBuildError(msg) from e
ploomber.exceptions.TaskBuildError: Exception when running on_finish for task 'sample'

ploomber.exceptions.TaskBuildError: Error building task 'sample': the task ran successfully but the product File('output/nb.ipynb') is missing. Ensure your code is generating it.
ploomber.exceptions.TaskBuildError: Exception when running on_finish for task 'sample'

```

2022-07-20 21:08 UTC, idomic requested changes
Comment above

2022-07-21 13:26 UTC, yafimvo commented
I've tried to run the same commands with the same `pipeline.yaml` on my local env and couldn't reproduce this error (receive "invalid extension message")

Did you run this command on your local env manually?

2022-07-22 15:12 UTC, idomic commented
/ok-to-test sha=f25aef9

2022-07-22 15:12 UTC, idomic approved these changes
After retrying looks like it works as expected!

2022-07-22 15:13 UTC, merged