start_method added to parallel executor
ploomber/ploomber pull request #927
Opened 2022-07-20 14:25 UTC by yafimvo

## Describe your changes
Added add a new start_method argument to Parallel.py and then initiated ProcessPoolExecutor with mp_context where context is default or the given start_method

* I can't connect to GPU locally so I need to test this code on AWS VM.

## Issue ticket number and link
Closes #882 
https://github.com/ploomber/ploomber/issues/882

## Checklist before requesting a review
- [X] I have performed a self-review of my code
- [ ] I have added thorough tests (when necessary).
- [ ] I have added the right documentation (when needed). Product update? If yes, write one line about this update.

2022-07-21 11:36 UTC, yafimvo commented
I've successfully reproduced this exception on AWS VM running the code on GPU with Cuda.
After running the new code it seems to work OK using following pipeline.yaml configuration:
```
executor:
  dotted_path: ploomber.executors.Parallel
  processes: 4
  start_method: spawn 
```

I also added a ValueType exception when `start_method` is incorrect (possible values are: `spawn, fork, forkserver`)

I'm not sure how to test this parallel behavior.

2022-07-21 12:46 UTC, idomic commented
Nice!

> I'm not sure how to test this parallel behavior.

You'd need to run a pipeline.yaml and tasks that has independent tasks that can run in parallel.
Check out [this grid feature](https://github.com/ploomber/projects/blob/cbcf4aee763d2eac33d0d749faa3807c9b7c07d9/cookbook/grid/README.md) pipeline.

2022-07-21 12:59 UTC, idomic commented on tests/dag/test_dag.py
> +@pytest.mark.parametrize('start_method', ["invalid_start_method_value"])
Also add a test on the other start methods and validate it's set in the context

2022-07-21 13:00 UTC, idomic requested changes
Looks good small comment, and missing the manual test on parallel execution

2022-07-22 15:25 UTC, idomic commented
/ok-to-test sha=dd0db89

2022-07-22 15:32 UTC, idomic approved these changes
Nice work!
For next PRs let's try starting with some tests and then develop (TDD)

2022-07-22 15:32 UTC, merged